version: "3"

services:
  database:
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}

    volumes:
      - db-data:/var/lib/postgresql/data:rw

  app:
    image: docker-backend
    restart: always
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-ChangeMe}@database:5432/${POSTGRES_DB:-app}
    depends_on:
      - database

  front:
    image: docker-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - database

volumes:
  db-data:
